steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - Dockerfile.build
  - -t
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/time-slicing/gpucr-so:$_TAG
  - .
images:
- asia-southeast1-docker.pkg.dev/$PROJECT_ID/time-slicing/gpucr-so:$_TAG
substitutions:
  _TAG: unrounded-v1
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: 200
timeout: 3600s
